### ISSUE TITLE
Clarification regarding semilocal heat flux expression

### ISSUE THREAD

**Issue by rfhari** [sirmarcel/gknet-archive#3]
Hi @sirmarcel,

I recently came across your publication on semi-local heat flux, and I found it very interesting. Thank you for implementing this!

However, I'm unsure about the derivation of equations 6 and 7. Specifically, in equation 6, although I understand how the second term is derived (i.e., when L and J atoms are the same), I'm not clear on how the first term is obtained. Could you please explain this or point me to some relevant literature?

**Comment by rfhari** [comment]
Actually I got the idea now. Thanks!

**Comment by sirmarcel** [comment]
Hey @rfhari , glad you figured it out :) You can also take a look at my [thesis](https://marcel.science/doctor/) for a more detailed derivation of all the formulas!
